### ISSUE TITLE
missing pointer for DG

### ISSUE THREAD

**Issue by marcovilla118** [microchip-pic-avr-solutions/veml3328_arduino_driver#1]
Dear All,

just checking the code and we found that for set the configuration are missing the pointer to the bit configuration for DG, GAIN etc..

Here for example is missing the bit position of the parameter DG (should be bit 12 and 13)

uint8_t VEMLClass::setDG(DG_t val) {
    regWrite(POINTER_CONFIG, val);

    /* Check user val */
    uint16_t reg = regRead(POINTER_CONFIG);
    if (!(reg & val)) {
#ifdef DEBUG
        SerialDebug.println("Error: DG not set");
#endif
        return 1;
    }

    return 0;
}

**Comment by M65649** [comment]
Hello @marcovilla118,

Thanks for notifying us, you're completely right. I don't know how that slipped past during release. I'll schedule an update to the driver as soon as possible. In the meantime, you can either left-shift the input (I see now that one has to be careful and read out the configuration each time one is writing as well) or modify the library directly. 

Again, thanks for letting us know.

**Comment by marcovilla118** [comment]
It's not so easy to understand how to fix it I need more study.

**Comment by M65649** [comment]
Hello @marcovilla118,

I've pushed the patch now here on GitHub. It should pop up in the Arduino library registry within a day or two.
